### ISSUE TITLE
Confusion about permission

### ISSUE THREAD

**Issue by buzzzo** [JeshuaEdgar/gal-sync-graph#1]
Hi

Your projects seems very interesting but it's not clear as to create app, especially the part regarding permission.
Could you please create a sort of step-by-step list in order to create the app ? or simply specify the step for the permission.

The azure interface is crappy and it's not useful at all their tutorial.

Thx

**Comment by JeshuaEdgar** [comment]
Hi @buzzzo !

Thanks for your interest! Cool to see somebody this early in the project. Remember that this is still early stages, so bugs will definitely appear.

 I shall try to update the Readme/Wiki on how to create an Azure AD Application with the right permissions.

**Comment by JeshuaEdgar** [comment]
Hi @buzzzo ,

I have just created a wiki page on how to create an Azure AD application with all the parameters that are required. Hope it helps you setting it up!

[Wiki link](https://github.com/JeshuaEdgar/gal-sync-graph/wiki/Creating-an-Azure-AD-Application)

Thanks
