### ISSUE TITLE
Problems connecting 

### ISSUE THREAD

**Issue by buzzzo** [JeshuaEdgar/gal-sync-graph#2]
I've receive the following error

The remote server returned an error: (401) Unauthorized.
At C:\o365\gal\Module\Public\func_Connect-GALSync.ps1:82 char:9
+         throw (Format-ErrorCode $_).ErrorMessage
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The remote serv...) Unauthorized.:String) [], RuntimeException
    + FullyQualifiedErrorId : The remote server returned an error: (401) Unauthorized.

Attached are my api permission on the app.[](url)
<img width="725" alt="Screenshot 2023-07-27 at 14 30 38" src="https://github.com/JeshuaEdgar/gal-sync-graph/assets/7355941/80d556c2-970c-455f-8730-1a67eb82ae61">

**Comment by buzzzo** [comment]
Nevermind, i've swapped secret id with secret value , but now i'm getting this:

Missing the  role(s), please update your application and rerun the script
At C:\o365\gal\Module\Public\func_Connect-GALSync.ps1:82 char:9
+         throw (Format-ErrorCode $_).ErrorMessage
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Missing the  ro...erun the script:String) [], RuntimeException
    + FullyQualifiedErrorId : Missing the  role(s), please update your application and rerun the script

**Comment by JeshuaEdgar** [comment]
@buzzzo 

For now, the quickfix should be adding the "Application.Read.All" API permission to the Azure AD Application. This is a bug, I will address this in the source code asap.

Let me know if it works!

**Comment by buzzzo** [comment]
Thx now it connect.

I'm trying to sync using an azure group 👍 
.\Sync-Contacts.ps1 -CredentialPath .\Credentials\credential.cred -Tenant xyz -ContactFolderName "GAL_Sync" -AzureADGroup "GAL_Users"

But i've receiving the following:

True
Get-GALAADGroupMembers : Cannot bind argument to parameter 'Name' because it is an empty string.
At C:\o365\gal\Sync-Contacts.ps1:27 char:74
+ ... up) { $mailBoxesToSync = Get-GALAADGroupMembers -Name $Target | Selec ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-GALAADGroupMembers], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-GALAADGroupMembers

Stop-Transcript : An error occurred stopping transcription: The host is not currently transcribing.
At C:\o365\gal\Sync-Contacts.ps1:41 char:1
+ Stop-Transcript
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Stop-Transcript], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.StopTranscriptCommand

**Comment by JeshuaEdgar** [comment]
Can you redownload the source from the repo? (via Code -> Download ZIP)

It should've fixed all your errors you are experiencing. Again let me know!

**Comment by buzzzo** [comment]
Thx ,much better but in the logs i've have:

PS>TerminatingError(New-FolderContact): "Cannot bind argument to parameter 'ContactFolder' because it is null."
2023/07/27 15:46:41 | Error | Failed to create contact
PS>TerminatingError(New-FolderContact): "Cannot bind argument to parameter 'ContactFolder' because it is null."
2023/07/27 15:46:41 | Error | Failed to create contact
PS>TerminatingError(New-FolderContact): "Cannot bind argument to parameter 'ContactFolder' because it is null."
2023/07/27 15:46:41 | Error | Failed to create contact
PS>TerminatingError(New-FolderContact): "Cannot bind argument to parameter 'ContactFolder' because it is null."
2023/07/27 15:46:41 | Error | Failed to create contact
PS>TerminatingError(New-FolderContact): "Cannot bind argument to parameter 'ContactFolder' because it is null."
2023/07/27 15:46:41 | Error | Failed to create contact
PS>TerminatingError(New-FolderContact): "Cannot bind argument to parameter 'ContactFolder' because it is null."


I run the script with:

PowerShell.exe -ExecutionPolicy Bypass ^
-File .\Sync-Contacts.ps1 -CredentialPath .\Credentials\credential.cred ^
-Tenant xyz ^
-ContactFolderName "GAL_Sync" ^
-AzureADGroup "GAL_Users" ^
-LogPath "%CD%\Logs"

**Comment by JeshuaEdgar** [comment]
Do you see in the logs that a folder has been created? Can you maybe check manually if the folder is present in the mailbox you are trying to sync.

Thanks!
